title: GeekPhotographer
description: Geek + Photos

url: https://www.geekphotographer.com
baseurl: ""
paginate_path: "/page:num/"
permalink: :title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Photos (SmugMug)
   url: http://photos.geekphotographer.com
 - title: Photos (Flickr)
   url: https://www.flickr.com/photos/lsmartman/

social:
   github: tiernano
   twitter: tiernano
   email: tiernan@tiernanotoole.ie

google_analytics: "UA-220614-3"
plugins: 
  -  jekyll-paginate
